EXTRA_CFLAGS += \
	-I$(rtext_dir)/include \
	-I$(rtfw_dir)/include \
	-I$(top_srcdir)/stack/include \
	-I$(top_builddir)/stack/include \
	-I$(srcdir) \
	$(rtnet_extradef) \
	-D__IN_RTNET__

obj-m += $(build_target).o

