#!/bin/sh

dir=`dirname $0`

usage() {
	cat << EOF
Usage:
	run server <client-ip> [options...]
	run client <server-ip> [options...]
	run stop
options:
	interval=<ms>
	packetsize=<bytes-without-header>
EOF
}

action=help
test "$1" && action=$1

case "$action" in
    server|client)
	test $# -ge 2 || { usage; exit 1; }
	ip=$2
	shift 2
	options="$*"
esac

case "$action" in
    server)
	modprobe rtai_fifos
	insmod $dir/server/rt_server.o client_ip_s=$ip $options
	;;

    client)
	modprobe rtai_fifos
	insmod $dir/client/rt_client.o server_ip_s=$ip $options
	$dir/client/showtime
	rmmod -r rt_client
	;;

    stop)
	killall showtime > /dev/null 2>&1
	rmmod -r rt_client > /dev/null 2>&1
	rmmod -r rt_server > /dev/null 2>&1
	;;

    *)
	usage
	exit 1
esac
