#!/bin/sh
if [ $# -lt 1 ]; then
	echo "tag-release release-number [<options>]"
	echo "(e.g.: tag-release 0.9.4 --username kiszka)"
	exit 1
fi

RELEASE=$1
shift 1

svn copy https://svn.sourceforge.net/svnroot/rtnet/trunk \
	https://svn.sourceforge.net/svnroot/rtnet/tags/rtnet-$RELEASE \
	-m "release $RELEASE" $*
