EXTRA_CFLAGS += \
	-I$(rtai_dir)/include \
	-I$(top_srcdir)/stack/include \
	-I$(top_builddir)/stack/include \
	-I$(srcdir) \
	$(rtnet_extradef) \
	-D__IN_RTNET__

obj-m += $(build_target).o

rt_tulip-objs := $(build_objs)
